name: metrics
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: victorpuntel
          template: classic
          base: header, activity, community
          config_timezone: America/Sao_Paulo
          
          # Language
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
